#pragma once

#include "NativeGameplayTags.h"

namespace MiniGameplayTags
{
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchWeapon);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_SpawnProtected);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reloading);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_AbilityInputBlocked);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Aim);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_MiniArena_Warmup);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_MiniArena_Playing);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_MiniArena_PostMatch);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Mini_RifleFire);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Mini_PistolFire);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Mini_Impact);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Mini_Damage);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Mini_Death);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Mini_Reload);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Mini_HitConfirmed);
}
