#pragma once

#include "NativeGameplayTags.h"

namespace MiniGameplayTags
{
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchWeapon);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	FPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);
}
